version: '3.7'
services:
  updates_db:
    # image: 'mongo:latest'
    # command: ['--replSet', 'rs0', '--bind_ip_all']
    # ports:
    #   - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    #   MONGO_INITDB_DATABASE: updates
    # volumes:
    #   - ./scripts/prepare-mongo-db.js:/docker-entrypoint-initdb.d/001_users.js:ro
    #   - ./.dev/updates/mongodb:/data/db
    image: bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: example
      MONGO_INITDB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: updates
    volumes:
      - ./scripts/prepare-mongo-db.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./.dev/updates/mongodb:/data/db
