version: "3.7"
services:
  updates_db:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_PORT=5432
      - POSTGRES_DB=updates
    ports:
      - 5432:5432
    volumes:
      - ./.dev/updates:/var/lib/postgresql/data

  updates_files:
    image: nginx
    ports:
      - 3090:80
    environment:
      - NGINX_PORT=80
    volumes:
      - ./.dev/updates-files:/usr/share/nginx/html

  broker:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
