version: "3.7"
services:
  updates_db:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_PORT=5432
      - POSTGRES_DB=updates
    ports:
      - 5432:5432
    volumes:
      - ./.dev/updates:/var/lib/postgresql/data
