name: CD - npm

on:
  # pull_request:
  # push:
  #   branches:
  #     - master
  workflow_run:
    workflows: ["CI"]
    # branches: [main]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo test
