name: CD - npm

on:
  # pull_request:
  # push:
  #   branches:
  #     - master
  workflow_run:
    workflows: ["CI"]
    # branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BAZELISK_CACHE_VERSION: 2
      BAZEL_CACHE_VERSION: 5
      GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo test
